### ISSUE TITLE
an error appears when I use blur

### ISSUE THREAD

**Issue by skriulle** [skriulle/image_test#3]
OpenCV Error: Assertion failed (0 <= anchor.x && anchor.x < ksize.width && 0 <= anchor.y && anchor.y < ksize.height) in init, file /tmp/opencv20160107-54198-1duzac3/opencv-2.4.12/modules/imgproc/src/filter.cpp, line 182
Traceback (most recent call last):
  File "app/app_test.py", line 166, in on_draw
    self.functions[self.current_function]()
  File "app/app_test.py", line 100, in smoothing
    self.show_result(md.smoothing(img,t1,t2))
  File "/Users/skriulle/rep/codes/image_test/app/module.py", line 16, in smoothing
    blur = cv2.blur(img,(w,h))
cv2.error: /tmp/opencv20160107-54198-1duzac3/opencv-2.4.12/modules/imgproc/src/filter.cpp:182: error: (-215) 0 <= anchor.x && anchor.x < ksize.width && 0 <= anchor.y && anchor.y < ksize.height in function init

**Comment by skriulle** [comment]
the value mustn't be 0
